sonar.projectKey=gestion_censo_angular
sonar.projectName=gestion_censo_angular
sonar.host.url=http://192.168.1.143:9090
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/entity/**,**/model/**,**/dto/**,**/environments/**
sonar.scm.provider=git
